repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-case-conflict
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
  - id: terraform_fmt

- repo: local
  hooks:
  - id: helm-lint
    name: helm lint
    entry: helm lint helm/my-nginx-chart/
    language: system
    pass_filenames: false
